### ISSUE TITLE
Conflicting assemblies (Ambiguous Invocation)

### ISSUE THREAD

**Issue by LiamVisionary** [MoralisWeb3/unity-web3-game-kit#107]
Hi, I have both Chainsafe's Unity SDK installed and now Moralis, but since installing Moralis, I've been getting an issue about ambiguous invocation. For example these 3 methods:

`        public bool IsVSignedForChain()
        {
            return V.ToBigIntegerFromRLPDecoded() >= 35;
        }

        public bool IsVSignedForLegacy()
        {
            var v = V.ToBigIntegerFromRLPDecoded();
            return v >= 27;
        }

        public bool IsVSignedForYParity()
        {
            var v = V.ToBigIntegerFromRLPDecoded();
            return v == 0 || v == 1;
        }`
        
        are ambiguously called V.ToBigIntegerFromRLPDecoded() since it exists both in the Netherium assembly and Assembly-CSharp-FirstPass.

In addition, WebSocket.jslib is conflicting with the one I'm using in my Photon networking plugin.

**Comment by KoenRijpstra** [comment]
The  WebSocket.jslib will be fixed in the next release

**Comment by KoenRijpstra** [comment]
WebSocket.jslib conflict is fixed in the latest 1.2.3 release! 🎉
