### ISSUE TITLE
Error: HTTP/1.1 400 Bad Request {"code":206,"error":"Insufficient auth."}

### ISSUE THREAD

**Issue by meta8block** [MoralisWeb3/unity-web3-game-kit#124]
My code:
public static async UniTask<MyCustomUser> UpdateBalance(string objectId, string balance)
    {
        MoralisQuery<_User> query = await Moralis.Query<_User>();
        MyCustomUser user = await query.WhereEqualTo("objectId", objectId).FirstOrDefaultAsync();
        await user.SaveAsync();
        return user;
    }

Errors:
Target: https://8rfg0qpzyxcm.usemoralis.com:2053/server/classes/_User/nzfrr0DP331GQNazYVrrSPWL
UnityEngine.Debug:LogError (object)

Error: HTTP/1.1 400 Bad Request
{"code":206,"error":"Insufficient auth."}

MoralisSaveException: {"code":206,"error":"Insufficient auth."}
MoralisUnity.Platform.Services.ClientServices.MoralisObjectService+<SaveAsync>d__11.MoveNext ()
![1](https://user-images.githubusercontent.com/66485123/186189265-641a890a-9922-4b7b-b859-90b9fb7e320d.PNG)

**Comment by meta8block** [comment]
signing massage has expired
This is a mistake of the developers
![3](https://user-images.githubusercontent.com/66485123/186251477-8971a98d-0e8c-4395-bc61-8c1d81491caf.PNG)

**Comment by xactant** [comment]
I am not sure the error you show in the image is related.

Here is some sample code for extending a user to create a custom user. I used this and it worked for me without error:

Sample User extension code:
```
using Cysharp.Threading.Tasks;
using MoralisUnity;
using MoralisUnity.Platform.Objects;
using MoralisUnity.Platform.Queries;

namespace Assets.Scripts
{
    /// <summary>
    /// Create your custom user object derived from MoralisUser.
    /// Here I created a user that holds an access level and 
    /// address properties.
    /// </summary>
    public class MyCustomUser : MoralisUser
    {
        public int AccessLevel { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }

        public MyCustomUser() { }

        public MyCustomUser(MoralisUser baseUser)
        {
            base.accounts = baseUser.accounts;
            base.ACL = baseUser.ACL;
            base.authData = baseUser.authData;
            base.createdAt = baseUser.createdAt;
            base.email = baseUser.email;
            base.ethAddress = baseUser.ethAddress;
            base.objectId = baseUser.objectId;
            base.sessionToken = baseUser.sessionToken;
            base.updatedAt = baseUser.updatedAt;
            base.username = baseUser.username;
            // Necessary step to make sure the customer user is saved to
            // the _User table and not a new table.
            base.ClassName = baseUser.ClassName;
        }
    }

    /// <summary>
    /// The whole purpose of this class is to trick the MoralisQuery to 
    /// target the "_User" table
    /// </summary>
    internal class _User : MyCustomUser { }

    /// <summary>
    /// This class provides some examples showing how to create a user and 
    /// then load it at need.
    /// </summary>
    public class CustomUserServiceExample
    {
        public static async UniTask<MyCustomUser> CreateUser(MoralisUser user, int accessLevel, string street, string city, string state, string postalCode, string country)
        {
            MyCustomUser newUser = new MyCustomUser(user);
            newUser.City = city;
            newUser.State = state;
            newUser.PostalCode = postalCode;
            newUser.Country = country;
            newUser.Street = street;
            newUser.AccessLevel = accessLevel;

            await newUser.SaveAsync();

            return newUser;
        }

        /// <summary>
        /// Loads a custom user object using the normal MoralisUser
        /// as a reference.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public static async UniTask<MyCustomUser> LoadFromUser(MoralisUser user)
        {
            return await LoadFromUser(user.objectId);
        }

        /// <summary>
        /// Loads a customer user using an objectId
        /// </summary>
        /// <param name="objectId"></param>
        /// <returns></returns>
        public static async UniTask<MyCustomUser> LoadFromUser(string objectId)
        {
            // Query using the _User object so query is against the "_User" table.
            MoralisQuery<_User> q = await Moralis.Query<_User>();

            _User user = await q.WhereEqualTo("objectId", objectId).FirstOrDefaultAsync();

            // Since _User is derived from MyCustomUser you can just return it
            // and it will be returned as a MyCustomUser.
            return user;
        }
    }
}
```

Here is sample code showing how I used the user extension:

```
   internal class Testor
    {
        public async static void TestStuff()
        {
            await CreateCustomUserTest();

            await GetCustomUserTest();
        }

        private static async UniTask CreateCustomUserTest()
        {
            MoralisUser user = await Moralis.GetUserAsync();

            await Assets.Scripts.CustomUserServiceExample.CreateUser(user, 4321, "555 My Street", "MyCity", "FL", "33809", "US");
        }

        private static async UniTask GetCustomUserTest()
        {
            MoralisUser user = await Moralis.GetUserAsync();

            Assets.Scripts.MyCustomUser myUser = await Assets.Scripts.CustomUserServiceExample.LoadFromUser(user.objectId);

            Debug.Log($"Street: {myUser.Street}, City: {myUser.City}, State: {myUser.State}, Zip: {myUser.PostalCode}");
        }
    }
    ```

**Comment by meta8block** [comment]
> I am not sure the error you show in the image is related.
> 
> Here is some sample code for extending a user to create a custom user. I used this and it worked for me without error:
> 
> Sample User extension code:
> 
> ```
> using Cysharp.Threading.Tasks;
> using MoralisUnity;
> using MoralisUnity.Platform.Objects;
> using MoralisUnity.Platform.Queries;
> 
> namespace Assets.Scripts
> {
>     /// <summary>
>     /// Create your custom user object derived from MoralisUser.
>     /// Here I created a user that holds an access level and 
>     /// address properties.
>     /// </summary>
>     public class MyCustomUser : MoralisUser
>     {
>         public int AccessLevel { get; set; }
>         public string Street { get; set; }
>         public string City { get; set; }
>         public string PostalCode { get; set; }
>         public string Country { get; set; }
>         public string State { get; set; }
> 
>         public MyCustomUser() { }
> 
>         public MyCustomUser(MoralisUser baseUser)
>         {
>             base.accounts = baseUser.accounts;
>             base.ACL = baseUser.ACL;
>             base.authData = baseUser.authData;
>             base.createdAt = baseUser.createdAt;
>             base.email = baseUser.email;
>             base.ethAddress = baseUser.ethAddress;
>             base.objectId = baseUser.objectId;
>             base.sessionToken = baseUser.sessionToken;
>             base.updatedAt = baseUser.updatedAt;
>             base.username = baseUser.username;
>             // Necessary step to make sure the customer user is saved to
>             // the _User table and not a new table.
>             base.ClassName = baseUser.ClassName;
>         }
>     }
> 
>     /// <summary>
>     /// The whole purpose of this class is to trick the MoralisQuery to 
>     /// target the "_User" table
>     /// </summary>
>     internal class _User : MyCustomUser { }
> 
>     /// <summary>
>     /// This class provides some examples showing how to create a user and 
>     /// then load it at need.
>     /// </summary>
>     public class CustomUserServiceExample
>     {
>         public static async UniTask<MyCustomUser> CreateUser(MoralisUser user, int accessLevel, string street, string city, string state, string postalCode, string country)
>         {
>             MyCustomUser newUser = new MyCustomUser(user);
>             newUser.City = city;
>             newUser.State = state;
>             newUser.PostalCode = postalCode;
>             newUser.Country = country;
>             newUser.Street = street;
>             newUser.AccessLevel = accessLevel;
> 
>             await newUser.SaveAsync();
> 
>             return newUser;
>         }
> 
>         /// <summary>
>         /// Loads a custom user object using the normal MoralisUser
>         /// as a reference.
>         /// </summary>
>         /// <param name="user"></param>
>         /// <returns></returns>
>         public static async UniTask<MyCustomUser> LoadFromUser(MoralisUser user)
>         {
>             return await LoadFromUser(user.objectId);
>         }
> 
>         /// <summary>
>         /// Loads a customer user using an objectId
>         /// </summary>
>         /// <param name="objectId"></param>
>         /// <returns></returns>
>         public static async UniTask<MyCustomUser> LoadFromUser(string objectId)
>         {
>             // Query using the _User object so query is against the "_User" table.
>             MoralisQuery<_User> q = await Moralis.Query<_User>();
> 
>             _User user = await q.WhereEqualTo("objectId", objectId).FirstOrDefaultAsync();
> 
>             // Since _User is derived from MyCustomUser you can just return it
>             // and it will be returned as a MyCustomUser.
>             return user;
>         }
>     }
> }
> ```
> 
> Here is sample code showing how I used the user extension:
> 
> ```
>    internal class Testor
>     {
>         public async static void TestStuff()
>         {
>             await CreateCustomUserTest();
> 
>             await GetCustomUserTest();
>         }
> 
>         private static async UniTask CreateCustomUserTest()
>         {
>             MoralisUser user = await Moralis.GetUserAsync();
> 
>             await Assets.Scripts.CustomUserServiceExample.CreateUser(user, 4321, "555 My Street", "MyCity", "FL", "33809", "US");
>         }
> 
>         private static async UniTask GetCustomUserTest()
>         {
>             MoralisUser user = await Moralis.GetUserAsync();
> 
>             Assets.Scripts.MyCustomUser myUser = await Assets.Scripts.CustomUserServiceExample.LoadFromUser(user.objectId);
> 
>             Debug.Log($"Street: {myUser.Street}, City: {myUser.City}, State: {myUser.State}, Zip: {myUser.PostalCode}");
>         }
>     }
>     ```
> ```

This only works for 20 seconds

**Comment by meta8block** [comment]
I need to be able to save the user at any time, not in the first 20 seconds.

**Comment by Zarbuz** [comment]
This issue is duplicated by #119 and #118

**Comment by meta8block** [comment]
> This issue is duplicated by #119 and #118

Oh Really? Then why are you silent and doing nothing?

**Comment by meta8block** [comment]
> I am not sure the error you show in the image is related.
> 
> Here is some sample code for extending a user to create a custom user. I used this and it worked for me without error:
> 
> Sample User extension code:
> 
> ```
> using Cysharp.Threading.Tasks;
> using MoralisUnity;
> using MoralisUnity.Platform.Objects;
> using MoralisUnity.Platform.Queries;
> 
> namespace Assets.Scripts
> {
>     /// <summary>
>     /// Create your custom user object derived from MoralisUser.
>     /// Here I created a user that holds an access level and 
>     /// address properties.
>     /// </summary>
>     public class MyCustomUser : MoralisUser
>     {
>         public int AccessLevel { get; set; }
>         public string Street { get; set; }
>         public string City { get; set; }
>         public string PostalCode { get; set; }
>         public string Country { get; set; }
>         public string State { get; set; }
> 
>         public MyCustomUser() { }
> 
>         public MyCustomUser(MoralisUser baseUser)
>         {
>             base.accounts = baseUser.accounts;
>             base.ACL = baseUser.ACL;
>             base.authData = baseUser.authData;
>             base.createdAt = baseUser.createdAt;
>             base.email = baseUser.email;
>             base.ethAddress = baseUser.ethAddress;
>             base.objectId = baseUser.objectId;
>             base.sessionToken = baseUser.sessionToken;
>             base.updatedAt = baseUser.updatedAt;
>             base.username = baseUser.username;
>             // Necessary step to make sure the customer user is saved to
>             // the _User table and not a new table.
>             base.ClassName = baseUser.ClassName;
>         }
>     }
> 
>     /// <summary>
>     /// The whole purpose of this class is to trick the MoralisQuery to 
>     /// target the "_User" table
>     /// </summary>
>     internal class _User : MyCustomUser { }
> 
>     /// <summary>
>     /// This class provides some examples showing how to create a user and 
>     /// then load it at need.
>     /// </summary>
>     public class CustomUserServiceExample
>     {
>         public static async UniTask<MyCustomUser> CreateUser(MoralisUser user, int accessLevel, string street, string city, string state, string postalCode, string country)
>         {
>             MyCustomUser newUser = new MyCustomUser(user);
>             newUser.City = city;
>             newUser.State = state;
>             newUser.PostalCode = postalCode;
>             newUser.Country = country;
>             newUser.Street = street;
>             newUser.AccessLevel = accessLevel;
> 
>             await newUser.SaveAsync();
> 
>             return newUser;
>         }
> 
>         /// <summary>
>         /// Loads a custom user object using the normal MoralisUser
>         /// as a reference.
>         /// </summary>
>         /// <param name="user"></param>
>         /// <returns></returns>
>         public static async UniTask<MyCustomUser> LoadFromUser(MoralisUser user)
>         {
>             return await LoadFromUser(user.objectId);
>         }
> 
>         /// <summary>
>         /// Loads a customer user using an objectId
>         /// </summary>
>         /// <param name="objectId"></param>
>         /// <returns></returns>
>         public static async UniTask<MyCustomUser> LoadFromUser(string objectId)
>         {
>             // Query using the _User object so query is against the "_User" table.
>             MoralisQuery<_User> q = await Moralis.Query<_User>();
> 
>             _User user = await q.WhereEqualTo("objectId", objectId).FirstOrDefaultAsync();
> 
>             // Since _User is derived from MyCustomUser you can just return it
>             // and it will be returned as a MyCustomUser.
>             return user;
>         }
>     }
> }
> ```
> 
> Here is sample code showing how I used the user extension:
> 
> ```
>    internal class Testor
>     {
>         public async static void TestStuff()
>         {
>             await CreateCustomUserTest();
> 
>             await GetCustomUserTest();
>         }
> 
>         private static async UniTask CreateCustomUserTest()
>         {
>             MoralisUser user = await Moralis.GetUserAsync();
> 
>             await Assets.Scripts.CustomUserServiceExample.CreateUser(user, 4321, "555 My Street", "MyCity", "FL", "33809", "US");
>         }
> 
>         private static async UniTask GetCustomUserTest()
>         {
>             MoralisUser user = await Moralis.GetUserAsync();
> 
>             Assets.Scripts.MyCustomUser myUser = await Assets.Scripts.CustomUserServiceExample.LoadFromUser(user.objectId);
> 
>             Debug.Log($"Street: {myUser.Street}, City: {myUser.City}, State: {myUser.State}, Zip: {myUser.PostalCode}");
>         }
>     }
>     ```
> ```

Where are you?

**Comment by xactant** [comment]
Looking further ...

**Comment by xactant** [comment]
There was a security update on the backend that now re-validates the signature everytime it is posted. I will need to add a patch for this in the Unity SDK. 

For now to get past the issue, before you call `user.SaveAsync()`, clear the authData array. For example:
```
user.authData.Clear();
await user.SaveAsync();
```

**Comment by meta8block** [comment]
> There was a security update on the backend that now re-validates the signature everytime it is posted. I will need to add a patch for this in the Unity SDK.
> 
> For now to get past the issue, before you call `user.SaveAsync()`, clear the authData array. For example:
> 
> ```
> user.authData.Clear();
> await user.SaveAsync();
> ```

Thanks, it works. 

Dear developers, please take a closer look at the problems. For a whole month you ignored the problem and said that everything was working

**Comment by xactant** [comment]
Re-open as I want to incorporate a solution into the SDK ...
