### ISSUE TITLE
Error: HTTP/1.1 403 Forbidden {"error":"unauthorized"}

### ISSUE THREAD

**Issue by Khaldi-Anouar** [MoralisWeb3/unity-web3-game-kit#125]
Hello, we were using Moralis for 5-6 months, everything works fine, we're working on WebGL game, our builds was working fine with unity 2020 and above, till decided to upgrade the unity version to 2021, we're having a problem and we're trying to fix it long time ago! the problem is happening when we try to login we're getting this error:

![error](https://user-images.githubusercontent.com/28868733/187846976-c709a3eb-bd4a-4169-baa5-215328ddd53e.png)

the problem is this problem is not happening on all devices and all browsers, for example if there's a windows where this game can work finely on chrome, and this game couldn't be work on other windows on chrome
we figures out that the `x-parse-application-id` (in request header) is missing in the browsers in which we're getting the error!

![x-app](https://user-images.githubusercontent.com/28868733/187847738-9eb8d1dc-df0c-4573-9c49-713c85d3deef.png)

Nb. when we create new empty  project and we import the Moralis assets then we take build, we're getting the same error with Unity 2021.3.7f1, but it works fine with Unity 2020. 
Can you help us to fix the problem?

Unity version: 2021.3.7f1
Web3 Game Kit version: v1.2.7
Development platform: Windows
Build platform: WebGL

**Comment by KoenRijpstra** [comment]
@Khaldi-Anouar Thanks for your report. Our team will see if this is something we can fix or maybe is a Unity 2021.3 bug.

**Comment by KoenRijpstra** [comment]
@Khaldi-Anouar I did a test with Unity 2021.3.8f1 and using Chrome version 105.0.5195.52 (Officiële build) (64-bits) and all seems to be working. Maybe Unity 2021.3.7f1 has a issue. Could you test with version 2021.3.8f1?

**Comment by Khaldi-Anouar** [comment]
> @Khaldi-Anouar I did a test with Unity 2021.3.8f1 and using Chrome version 105.0.5195.52 (Officiële build) (64-bits) and all seems to be working. Maybe Unity 2021.3.7f1 has a issue. Could you test with version 2021.3.8f1?

Hello, I tried with unity 2021.3.8f1 (Empty project with moralis), it doesn't work
can you try on different browsers please?

**Comment by KoenRijpstra** [comment]
Which browser are you using? Does the introduction scene work?

**Comment by Khaldi-Anouar** [comment]
@KoenRijpstra yeah everything works fine until I click on connect and I sign with Metamask
this is the build link https://crimin.itch.io/newmoralis

**Comment by KoenRijpstra** [comment]
Which browser are you testing on?

**Comment by Khaldi-Anouar** [comment]
More than one browser! chrome, opera, edge, brave, in some computers it's working on them all, is some computers it working only in some of them, in some computers it doesn't work on all of them

**Comment by KoenRijpstra** [comment]
@Khaldi-Anouar We tested on multiple browser and can't replicate the issue. If it is working on some computers and not on others what is the difference between those computers?

**Comment by ahmetkucukkuru** [comment]
Same problem.
https://forum.moralis.io/t/unity-moralis-v1-2-7-unauthorized-problem/19297/10
I am using Unity 2021.3.9f1 (latest stable) and i created empty project. And i added moralis v1.2.7 (latest). Also, i created ropsten test server with moralis. But when i try to connect with my metamask wallet, it has many errors. How can i fix?
![image](https://user-images.githubusercontent.com/94826681/188514112-c76d4e6a-a7ff-4749-8761-044a798efa80.png)

**Comment by newbiedev1** [comment]
Same problem:
https://forum.moralis.io/t/unity-moralis-v1-2-7-unauthorized-problem/19297/10
I am using Unity 2021.3.9f1 (latest stable) and i created empty project. And i added moralis v1.2.7 (latest). Also, i created ropsten test server with moralis. But when i try to connect with my metamask wallet, it has many errors. How can i fix?
Note: I am trying on Unity Editor.
![image](https://user-images.githubusercontent.com/112906910/188514782-a048319e-51f4-4b05-a7aa-78ba90697e8b.png)

**Comment by newbiedev1** [comment]
> @Khaldi-Anouar I did a test with Unity 2021.3.8f1 and using Chrome version 105.0.5195.52 (Officiële build) (64-bits) and all seems to be working. Maybe Unity 2021.3.7f1 has a issue. Could you test with version 2021.3.8f1?

I installed 2021.3.8f1 and tried with moralis v1.2.7 sdk on Unity Editor. But it's not working. Wallet cannot connect.
![image](https://user-images.githubusercontent.com/112906910/188587823-bf37d8fb-d75b-4057-b5e4-0ed00d8bb23c.png)

**Comment by KoenRijpstra** [comment]
@Khaldi-Anouar @newbiedev1 Which version of the Moralis server is your dapp running? You can find it in your admin dashboard: 
![image](https://user-images.githubusercontent.com/579455/188611462-0b9358b8-66a4-46a6-9e53-e4ee147da493.png)

**Comment by newbiedev1** [comment]
> @Khaldi-Anouar @newbiedev1 Which version of the Moralis server is your dapp running? You can find it in your admin dashboard: ![image](https://user-images.githubusercontent.com/579455/188611462-0b9358b8-66a4-46a6-9e53-e4ee147da493.png)
Server version: v0.0.385

**Comment by Khaldi-Anouar** [comment]
@newbiedev1 same like you version, my version is v0.0.385

**Comment by newbiedev1** [comment]
> > @Khaldi-Anouar @newbiedev1 Which version of the Moralis server is your dapp running? You can find it in your admin dashboard: ![image](https://user-images.githubusercontent.com/579455/188611462-0b9358b8-66a4-46a6-9e53-e4ee147da493.png)
> > I am using v0.0.385 server version. Also, i tried with moralis v1.1.0 and wallet connection is working on Unity Editor. But latest moralis sdks are not working (i tried with v1.2.5 and v1.2.7).

Unity version: 2021.3.8f1
Moralis SDK version: v1.2.7
Server version: v0.0.385
 i created empty project. And i added moralis v1.2.7 (latest). Also, i created ropsten test server with moralis. But when i try to connect with my metamask wallet, it has many errors. I have no problem with moralis v1.1.0 skd. 
 
![image](https://user-images.githubusercontent.com/112906910/188619799-c9d241b7-bf01-4d24-aae0-85acf4d97109.png)
![image](https://user-images.githubusercontent.com/112906910/188619921-b6382249-58f6-429c-b95d-06c6ce882af1.png)
![image](https://user-images.githubusercontent.com/112906910/188620420-924593c5-5585-4654-a110-d0fa5a0ffd60.png)

**Comment by newbiedev1** [comment]
Isn't there a solution?

**Comment by xactant** [comment]
At this time we have tried every combination given to us and we have not been able to replicate this issue.

Please do this:
1. Open your project in Visual Studio.
2. In the Solution Explorer, find and open this file: Packages / io.moralis.web3-unity-sdk / Runtime / Core / Platform / Services / MoralisCommandRunner.cs
3. Go to line 60 `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd); //, uploadProgress, downloadProgress, cancellationToken);`
4. Go to line 60: `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd);`
5. Add this code:
```
foreach (KeyValuePair<string, string> kvp in cmd.Headers)
            { 
                Debug.Log($"{kvp.Key}: {kvp.Value}");
            }
            ```
            5a.  If the `Debug` is not found, add a `using UnityEngine;` statement at the top of the file.
6. Run the app.
7. At authentication, if you receive the error, check the Console log. 
8. If the headers were logged, please copy these as TEXT and post them in a new comment.
9. If the headers were not logged something else is going on. Please go to your Moralis Server logs. If there are errors please copy the last error logged in a new comment. 

Thank you.

**Comment by newbiedev1** [comment]
> At this time we have tried every combination given to us and we have not been able to replicate this issue.
> 
> Please do this:
> 
> 1. Open your project in Visual Studio.
> 2. In the Solution Explorer, find and open this file: Packages / io.moralis.web3-unity-sdk / Runtime / Core / Platform / Services / MoralisCommandRunner.cs
> 3. Go to line 60 `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd); //, uploadProgress, downloadProgress, cancellationToken);`
> 4. Go to line 60: `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd);`
> 5. Add this code:
> 
> ```
> foreach (KeyValuePair<string, string> kvp in cmd.Headers)
>             { 
>                 Debug.Log($"{kvp.Key}: {kvp.Value}");
>             }
> ```
> 
> 5a. If the `Debug` is not found, add a `using UnityEngine;` statement at the top of the file. 6. Run the app. 7. At authentication, if you receive the error, check the Console log. 8. If the headers were logged, please copy these as TEXT and post them in a new comment. 9. If the headers were not logged something else is going on. Please go to your Moralis Server logs. If there are errors please copy the last error logged in a new comment.
> 
> Thank you.

Thank you for reply. Debug.log:

Content-Type: application/json
UnityEngine.Debug:Log (object)
MoralisUnity.Platform.Services.ClientServices.MoralisCommandRunner`1/<RunCommandAsync>d__17<MoralisUnity.Platform.Objects.MoralisUser>:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/MoralisCommandRunner.cs:64)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<MoralisUnity.Platform.Services.ClientServices.MoralisCommandRunner`1/<RunCommandAsync>d__17<MoralisUnity.Platform.Objects.MoralisUser>, System.Tuple`2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.Tuple`2<System.Net.HttpStatusCode, string>>:TrySetResult (System.Tuple`2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple`2<System.Net.HttpStatusCode, string>>:SetResult (System.Tuple`2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/UniversalWebClient.cs:114)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple`2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent ()

**Comment by newbiedev1** [comment]
> At this time we have tried every combination given to us and we have not been able to replicate this issue.
> 
> Please do this:
> 
> 1. Open your project in Visual Studio.
> 2. In the Solution Explorer, find and open this file: Packages / io.moralis.web3-unity-sdk / Runtime / Core / Platform / Services / MoralisCommandRunner.cs
> 3. Go to line 60 `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd); //, uploadProgress, downloadProgress, cancellationToken);`
> 4. Go to line 60: `Tuple<Status, string> cmdResult = await GetWebClient().ExecuteAsync(cmd);`
> 5. Add this code:
> 
> ```
> foreach (KeyValuePair<string, string> kvp in cmd.Headers)
>             { 
>                 Debug.Log($"{kvp.Key}: {kvp.Value}");
>             }
> ```
> 
> 5a. If the `Debug` is not found, add a `using UnityEngine;` statement at the top of the file. 6. Run the app. 7. At authentication, if you receive the error, check the Console log. 8. If the headers were logged, please copy these as TEXT and post them in a new comment. 9. If the headers were not logged something else is going on. Please go to your Moralis Server logs. If there are errors please copy the last error logged in a new comment.
> 
> Thank you.

Are there any solution 🙂

**Comment by Khaldi-Anouar** [comment]
Hello @xactant
I tried what you ask then I took a WebGl build, the headers are current in both devices (device A where we can and device B where we can't login)
both of them are giving the same debugs, but when I check the headers, there's some missing parameters `x-parse-installation-id` and `x-parse-application-id`
This is the device A (or browser A) no missing headers:
![NoError](https://user-images.githubusercontent.com/28868733/189841273-bbf33d08-dfdd-4a2c-ba02-5eb8081a309b.png)
This is the device B (or browser B) with missing headers
<img width="887" alt="WithError" src="https://user-images.githubusercontent.com/28868733/189843944-b6385efd-9723-4ba8-a92b-16a0497c846b.png">

**Comment by KoenRijpstra** [comment]
@Khaldi-Anouar Does this only happen with users on Turkish networks?
