### ISSUE TITLE
v1.2.7 Unauthorized Problem

### ISSUE THREAD

**Issue by newbiedev1** [MoralisWeb3/unity-web3-game-kit#127]
I am using Unity 2021.3.9f1 (latest stable) and i created empty project. And i added moralis v1.2.7 (latest). Also, i created ropsten test server with moralis. But when i try to connect with my metamask wallet, it has many errors. How can i fix? I tested Unity 2021.3.3f1, 2021.3.4f1, 2021.3.8f1, 2021.3.9f1, 2020.3.0f1. Also, i used moralis 1.2.5 and 1.2.7. Same error on all of them. Metamask wallet did not connect. But , i have tested with moralis old sdk (v1.1.0) and unity 2021.3.9f1, there is no problem and wallet connection is working. I don’t understand :(
![image](https://user-images.githubusercontent.com/112906910/189296011-168270ff-bb72-4760-81ae-2774cefd9f49.png)
![image](https://user-images.githubusercontent.com/112906910/189296031-00752b33-003a-4c4c-bdc3-373f61b6cfc4.png)
![image](https://user-images.githubusercontent.com/112906910/189295696-57e87410-8c81-48e9-95b0-9f685d10eb90.png)

First error:
Target: https://dhwor46zhuia.usemoralis.com:2053/server/users
UnityEngine.Debug:LogError (object)
MoralisUnity.Platform.Services.UniversalWebClient/d__7:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/UniversalWebClient.cs:87)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent ()

Second error:
Error: HTTP/1.1 403 Forbidden
{"error":"unauthorized"}
UnityEngine.Debug:LogError (object)
MoralisUnity.Platform.Services.UniversalWebClient/d__7:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/UniversalWebClient.cs:88)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent ()

Warning error:
LogInAsync failed: {"error":"unauthorized"}
UnityEngine.Debug:Log (object)
MoralisUnity.Platform.Services.ClientServices.MoralisUserService1/<LogInAsync>d__19<MoralisUnity.Platform.Objects.MoralisUser>:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/MoralisUserService.cs:106) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.ClientServices.MoralisUserService1/<LogInAsync>d__19<MoralisUnity.Platform.Objects.MoralisUser>, MoralisUnity.Platform.Objects.MoralisUser>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313) Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTask.cs:21) Cysharp.Threading.Tasks.UniTaskCompletionSourceCore1<System.Tuple2<System.Net.HttpStatusCode, string>>:TrySetResult (System.Tuple2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.ClientServices.MoralisCommandRunner1/d__17<MoralisUnity.Platform.Objects.MoralisUser>, System.Tuple2<System.Net.HttpStatusCode, string>>:SetResult (System.Tuple2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
MoralisUnity.Platform.Services.ClientServices.MoralisCommandRunner1/<RunCommandAsync>d__17<MoralisUnity.Platform.Objects.MoralisUser>:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/MoralisCommandRunner.cs:88) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.ClientServices.MoralisCommandRunner1/<RunCommandAsync>d__17<MoralisUnity.Platform.Objects.MoralisUser>, System.Tuple2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore1<System.Tuple2<System.Net.HttpStatusCode, string>>:TrySetResult (System.Tuple2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/UniTaskCompletionSource.cs:139) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.UniversalWebClient/d__7, System.Tuple2<System.Net.HttpStatusCode, string>>:SetResult (System.Tuple2<System.Net.HttpStatusCode, string>) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
MoralisUnity.Platform.Services.UniversalWebClient/d__7:MoveNext () (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/UniversalWebClient.cs:114)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple2<System.Net.HttpStatusCode, string>>:Run () (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent ()

Third error:
NullReferenceException: Object reference not set to an instance of an object
MoralisUnity.Platform.Services.ClientServices.UserServiceExtensions.LogInWithAsync[TUser] (MoralisUnity.Platform.Abstractions.IServiceHub1[TUser] serviceHub, System.String authType, System.Collections.Generic.IDictionary2[TKey,TValue] data, System.Threading.CancellationToken cancellationToken) (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Platform/Services/ClientServices/UserServiceExtensions.cs:202)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2[TStateMachine,T].GetResult (System.Int16 token) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:342) MoralisUnity.MoralisClient.LogInAsync (System.Collections.Generic.IDictionary2[TKey,TValue] data, System.Threading.CancellationToken cancellationToken) (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/MoralisClient.cs:221)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2[TStateMachine,T].GetResult (System.Int16 token) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:342) MoralisUnity.Moralis.LogInAsync (System.Collections.Generic.IDictionary2[TKey,TValue] authData, System.Int32 chainId) (at Packages/io.moralis.web3-unity-sdk/Runtime/Core/Moralis.cs:320)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Packages/io.moralis.web3-unity-sdk/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:342)
MoralisUnity.Kits.AuthenticationKit.AuthenticationKit.WalletConnect_SignAndLoginToMoralis (WalletConnectSharp.Unity.WalletConnectUnitySession session) (at Packages/io.moralis.web3-unity-sdk/Runtime/Kits/AuthenticationKit/Scripts/AuthenticationKit.cs:387)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.b__7_0 (System.Object state) (at <6073cf49ed704e958b8a66d540dea948>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at :0)
UnityEngine.UnitySynchronizationContext.Exec () (at :0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at :0)

**Comment by newbiedev1** [comment]
Today, i tried on Mac OS. I created new empty project and installed 1.2.7 game kit. Wallet connection is working perfectly on Unity Editor with metamask scanning.
Unity version: 2021.3.9f1 apple silicon
Game kit version: 1.2.7
After that, I switched target to WebGL. But, i do not have moraliswebgl template in player settings.
![image](https://user-images.githubusercontent.com/112906910/189480665-8ec120d3-a8b5-46fd-80d4-2509e0fa249b.png)
So i build webgl and open with chrome. Now, i have this errors:
![image](https://user-images.githubusercontent.com/112906910/189480691-14789594-40e9-4d46-ae0e-48709d2aa0ec.png)

**Comment by xactant** [comment]
@newbiedev1 

I am not able to reproduce with a clean build.

Please check the moralis serverlogs. Any errors when you attempt login?
Debug through LoginAsync - is the Application Id (DappId) header being set?

**Comment by newbiedev1** [comment]
> @newbiedev1
> 
> I am not able to reproduce with a clean build.
> 
> Please check the moralis serverlogs. Any errors when you attempt login? Debug through LoginAsync - is the Application Id (DappId) header being set?

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/112906910/190977565-c2a62022-b5e5-4422-bb5a-ff4f13308f18.png">

ArgumentNullException: Value cannot be null.
Parameter name: obj
  at System.Threading.Monitor.ReliableEnterTimeout (System.Object obj, System.Int32 timeout, System.Boolean& lockTaken) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---



_JS_Log_Dump @ Build.framework.js.br:3
$func12226 @ Build.wasm.br:0x397959
$func108019 @ Build.wasm.br:0x1a84acb
$func49090 @ Build.wasm.br:0xdefba5
$func595 @ Build.wasm.br:0xb79d5
$func15837 @ Build.wasm.br:0x463faa
$func1120 @ Build.wasm.br:0xc83e6
$func1696 @ Build.wasm.br:0xe4a71
$func110796 @ Build.wasm.br:0x1aeaee8
$func50797 @ Build.wasm.br:0xf881f8
$func50797 @ Build.wasm.br:0xf88269
$func49069 @ Build.wasm.br:0xded20d
$wj @ Build.wasm.br:0x1a6580b
browserIterationFunc @ Build.framework.js.br:3
callUserCallback @ Build.framework.js.br:3
runIter @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3
requestAnimationFrame (async)
requestAnimationFrame @ Build.framework.js.br:3
Browser_mainLoop_scheduler_rAF @ Build.framework.js.br:3
Browser_mainLoop_runner @ Build.framework.js.br:3

**Comment by newbiedev1** [comment]
> @newbiedev1
> 
> I am not able to reproduce with a clean build.
> 
> Please check the moralis serverlogs. Any errors when you attempt login? Debug through LoginAsync - is the Application Id (DappId) header being set?

Server Logs:
Get all logs in your terminal: [Learn about Moralis CLI](https://docs.moralis.io/moralis-server/tools/moralis-admin-cli#get-logs)
2022-09-19T11:19:58.812Z - Ran cloud function coreservices_getChains for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chainId":"0x3","exchange":"ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T11:19:58.798Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T11:19:58.447Z - Ran cloud function coreservices_listEventSyncStatus for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"results":[]}}
2022-09-19T11:19:51.353Z - Ran cloud function coreservices_getChains for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chainId":"0x3","exchange":"ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T11:19:51.341Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T11:00:43.431Z - Ran cloud function pluginsReady for user undefined with:
  Input: {}
  Result: true
2022-09-19T11:00:43.416Z - Create new client: 11a360d0-512d-4ce4-8ec7-77a2db755b74
2022-09-19T11:00:24.631Z - Initialized Function plugin customUserPlugin
2022-09-19T11:00:24.629Z - Initialized customUserPlugin
2022-09-19T11:00:24.624Z - Initialized plugin ./convenience/tracker
2022-09-19T11:00:24.615Z - Initialized plugin ./convenience/index
2022-09-19T11:00:24.400Z - Initialized plugin ./server
2022-09-19T11:00:24.394Z - Initialized plugin ./evm/watchContractEvent
2022-09-19T11:00:24.283Z - Initialized plugin ./evm/historical/accountApiFunctions
2022-09-19T11:00:24.278Z - Initialized plugin ./evm/historical/historicalApiFunctions
2022-09-19T11:00:24.241Z - Initialized plugin ./coreservices/index
2022-09-19T11:00:24.238Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T11:00:24.225Z - Ran cloud function coreservices_getOrganization for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":{"id":"185492","speedyTokenSignature":"cce3ecf02d66d721b7ca1bf7ed68c4e2307112dafb21f93baa41e69a5ec2858a"}}}
2022-09-19T11:00:24.192Z - Initialized Function plugin loadPlugins
2022-09-19T11:00:24.112Z - Ran cloud function checkSessionToken for user DGnLVGzXfsyerHSELMOIPl1P with:
  Input: {}
  Result: true
2022-09-19T11:00:24.029Z - Plugin coreservices is healthy.
2022-09-19T11:00:23.975Z - Migration 0.0.1 Applied Correctly
2022-09-19T11:00:21.485Z - Parse LiveQuery Server starts running
2022-09-19T10:00:34.758Z - Ran cloud function pluginsReady for user undefined with:
  Input: {}
  Result: true
2022-09-19T10:00:34.743Z - Create new client: 22bab817-724c-420d-838e-e3480c2f181c
2022-09-19T10:00:32.232Z - Initialized Function plugin customUserPlugin
2022-09-19T10:00:32.231Z - Initialized customUserPlugin
2022-09-19T10:00:32.225Z - Initialized plugin ./convenience/tracker
2022-09-19T10:00:32.216Z - Initialized plugin ./convenience/index
2022-09-19T10:00:31.988Z - Initialized plugin ./server
2022-09-19T10:00:31.980Z - Initialized plugin ./evm/watchContractEvent
2022-09-19T10:00:31.869Z - Initialized plugin ./evm/historical/accountApiFunctions
2022-09-19T10:00:31.863Z - Initialized plugin ./evm/historical/historicalApiFunctions
2022-09-19T10:00:31.822Z - Initialized plugin ./coreservices/index
2022-09-19T10:00:31.818Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T10:00:31.805Z - Ran cloud function coreservices_getOrganization for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":{"id":"185492","speedyTokenSignature":"cce3ecf02d66d721b7ca1bf7ed68c4e2307112dafb21f93baa41e69a5ec2858a"}}}
2022-09-19T10:00:31.777Z - Initialized Function plugin loadPlugins
2022-09-19T10:00:31.663Z - Ran cloud function checkSessionToken for user DGnLVGzXfsyerHSELMOIPl1P with:
  Input: {}
  Result: true
2022-09-19T10:00:31.555Z - Plugin coreservices is healthy.
2022-09-19T10:00:31.500Z - Migration 0.0.1 Applied Correctly
2022-09-19T10:00:29.225Z - Parse LiveQuery Server starts running
2022-09-19T09:13:54.406Z - Ran cloud function coreservices_getChains for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chainId":"0x3","exchange":"ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T09:13:54.377Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T09:00:37.039Z - Ran cloud function pluginsReady for user undefined with:
  Input: {}
  Result: true
2022-09-19T09:00:36.711Z - Initialized Function plugin customUserPlugin
2022-09-19T09:00:36.710Z - Initialized customUserPlugin
2022-09-19T09:00:36.704Z - Initialized plugin ./convenience/tracker
2022-09-19T09:00:36.695Z - Initialized plugin ./convenience/index
2022-09-19T09:00:36.463Z - Initialized plugin ./server
2022-09-19T09:00:36.455Z - Initialized plugin ./evm/watchContractEvent
2022-09-19T09:00:36.332Z - Initialized plugin ./evm/historical/accountApiFunctions
2022-09-19T09:00:36.326Z - Initialized plugin ./evm/historical/historicalApiFunctions
2022-09-19T09:00:36.290Z - Initialized plugin ./coreservices/index
2022-09-19T09:00:36.286Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T09:00:36.275Z - Ran cloud function coreservices_getOrganization for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":{"id":"185492","speedyTokenSignature":"cce3ecf02d66d721b7ca1bf7ed68c4e2307112dafb21f93baa41e69a5ec2858a"}}}
2022-09-19T09:00:36.252Z - Initialized Function plugin loadPlugins
2022-09-19T09:00:36.137Z - Ran cloud function checkSessionToken for user DGnLVGzXfsyerHSELMOIPl1P with:
  Input: {}
  Result: true
2022-09-19T09:00:36.070Z - Plugin coreservices is healthy.
2022-09-19T09:00:36.039Z - Migration 0.0.1 Applied Correctly
2022-09-19T09:00:35.928Z - Create new client: 98ef7e60-2887-4c01-80c4-4c34d603d6b9
2022-09-19T09:00:33.661Z - Parse LiveQuery Server starts running
2022-09-19T08:23:25.065Z - Ran cloud function getServerTime for user undefined with:
  Input: {}
  Result: {"dateTime":1663575805063}
2022-09-19T05:00:29.127Z - Ran cloud function pluginsReady for user undefined with:
  Input: {}
  Result: true
2022-09-19T05:00:29.112Z - Create new client: 45754420-546d-4732-b787-0926a023b191
2022-09-19T05:00:22.048Z - Initialized Function plugin customUserPlugin
2022-09-19T05:00:22.047Z - Initialized customUserPlugin
2022-09-19T05:00:22.042Z - Initialized plugin ./convenience/tracker
2022-09-19T05:00:22.035Z - Initialized plugin ./convenience/index
2022-09-19T05:00:21.841Z - Initialized plugin ./server
2022-09-19T05:00:21.834Z - Initialized plugin ./evm/watchContractEvent
2022-09-19T05:00:21.718Z - Initialized plugin ./evm/historical/accountApiFunctions
2022-09-19T05:00:21.711Z - Initialized plugin ./evm/historical/historicalApiFunctions
2022-09-19T05:00:21.674Z - Initialized plugin ./coreservices/index
2022-09-19T05:00:21.671Z - Ran cloud function coreservices_getProviders for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":[{"chain":"Eth","name":"Ropsten","network":"testnet","exchange":"ropsten","chainId":"0x3","lookups":["testnet","0x3","ropsten"],"token":{"name":"Ether","symbol":"ETH"},"httpProviderUrl":"eth/ropsten","maxRecordsPerCategory":50,"userSync":true}]}}
2022-09-19T05:00:21.658Z - Ran cloud function coreservices_getOrganization for user undefined with:
  Input: {}
  Result: {"status":200,"data":{"success":true,"result":{"id":"185492","speedyTokenSignature":"cce3ecf02d66d721b7ca1bf7ed68c4e2307112dafb21f93baa41e69a5ec2858a"}}}
2022-09-19T05:00:21.635Z - Initialized Function plugin loadPlugins
2022-09-19T05:00:21.506Z - Ran cloud function checkSessionToken for user DGnLVGzXfsyerHSELMOIPl1P with:
  Input: {}
  Result: true
2022-09-19T05:00:21.422Z - Plugin coreservices is healthy.
2022-09-19T05:00:21.374Z - Migration 0.0.1 Applied Correctly
2022-09-19T05:00:19.339Z - Parse LiveQuery Server starts running
