### ISSUE TITLE
SDK No longer works with Moralis V2 or Self Hosted V1

### ISSUE THREAD

**Issue by Denchyaknow** [MoralisWeb3/unity-web3-game-kit#130]
Followed this post:
https://forum.moralis.io/t/using-unity-sdk-with-self-hosted-server/20527
Migrated to Self Hosting DB on Heroku
Auth working fine,
But no DB functions work,
no SaveAsync()
No Moralis.Query()
Nothing, even tho our Self Hosted Sever logs our login, Auth works fine in Unity side.

Clueless even if we pay moralis and dont go self hosted route.
Docs not helpful in migrating our project from this SDK.

**Comment by dpradell-moralis** [comment]
Hi @Denchyaknow did you set up a DB on MongoDB like explained [here](https://docs.moralis.io/web3-data-api/self-hosted-moralis-server/run-parse-server-locally#c-use-hosted-mongodb-atlas-hosted)? I just tested it and everything is working fine
